require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/selected_plants", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SelectedPlant. As you add validations to SelectedPlant, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SelectedPlant.create! valid_attributes
      get selected_plants_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      selected_plant = SelectedPlant.create! valid_attributes
      get selected_plant_url(selected_plant)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_selected_plant_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      selected_plant = SelectedPlant.create! valid_attributes
      get edit_selected_plant_url(selected_plant)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SelectedPlant" do
        expect {
          post selected_plants_url, params: { selected_plant: valid_attributes }
        }.to change(SelectedPlant, :count).by(1)
      end

      it "redirects to the created selected_plant" do
        post selected_plants_url, params: { selected_plant: valid_attributes }
        expect(response).to redirect_to(selected_plant_url(SelectedPlant.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SelectedPlant" do
        expect {
          post selected_plants_url, params: { selected_plant: invalid_attributes }
        }.to change(SelectedPlant, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post selected_plants_url, params: { selected_plant: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested selected_plant" do
        selected_plant = SelectedPlant.create! valid_attributes
        patch selected_plant_url(selected_plant), params: { selected_plant: new_attributes }
        selected_plant.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the selected_plant" do
        selected_plant = SelectedPlant.create! valid_attributes
        patch selected_plant_url(selected_plant), params: { selected_plant: new_attributes }
        selected_plant.reload
        expect(response).to redirect_to(selected_plant_url(selected_plant))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        selected_plant = SelectedPlant.create! valid_attributes
        patch selected_plant_url(selected_plant), params: { selected_plant: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested selected_plant" do
      selected_plant = SelectedPlant.create! valid_attributes
      expect {
        delete selected_plant_url(selected_plant)
      }.to change(SelectedPlant, :count).by(-1)
    end

    it "redirects to the selected_plants list" do
      selected_plant = SelectedPlant.create! valid_attributes
      delete selected_plant_url(selected_plant)
      expect(response).to redirect_to(selected_plants_url)
    end
  end
end
